version: "3"

rpc:
  listen: "tcp://127.0.0.1:6001"

server:
  command: "php bootstrap.php"
  relay: "pipes"

grpc:
  listen: "0.0.0.0:50051"
  proto:
    - "protos/messages.proto"
  workers:
    pool:
      numWorkers: 1
